# Generated by Django 6.0 on 2025-12-15 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpsrecord",
            name="weight",
            field=models.FloatField(
                blank=True, help_text="Vehicle load weight (kg), optional", null=True
            ),
        ),
        migrations.CreateModel(
            name="CrowdingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "occupancy_ratio",
                    models.FloatField(help_text="Estimated occupancy ratio (0-1+)"),
                ),
                ("level", models.CharField(max_length=20)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bus"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ETARecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_timestamp",
                    models.DateTimeField(help_text="Timestamp of the GPS record used"),
                ),
                ("eta_seconds", models.IntegerField(blank=True, null=True)),
                ("eta_minutes", models.FloatField(blank=True, null=True)),
                ("distance_m", models.FloatField(blank=True, null=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bus"
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.busstop"
                    ),
                ),
            ],
        ),
    ]
